-- The Mirror Project - Oracle 11g-compatible foundation
-- Run once while connected to the approved FRSCMP schema.
-- Oracle DDL auto-commits. Review and back up before execution.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE SEQUENCE MIRROR_USERS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MIRROR_OTP_REQ_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MIRROR_SESSIONS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MIRROR_POTHOLES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MIRROR_REPORTS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MIRROR_PHOTOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MIRROR_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MIRROR_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MIRROR_USERS (
  id NUMBER(19) NOT NULL,
  name NVARCHAR2(150) NOT NULL,
  phone VARCHAR2(20 CHAR) NOT NULL,
  email VARCHAR2(254 CHAR),
  role VARCHAR2(30 CHAR) DEFAULT 'citizen' NOT NULL,
  phone_verified NUMBER(1) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_USERS PRIMARY KEY (id),
  CONSTRAINT UK_MIRROR_USERS_PHONE UNIQUE (phone),
  CONSTRAINT CK_MIRROR_USERS_ROLE CHECK (
    role IN ('citizen', 'officer', 'service_provider', 'admin', 'super_admin')
  ),
  CONSTRAINT CK_MIRROR_USERS_VER CHECK (phone_verified IN (0, 1))
);

CREATE TABLE MIRROR_OTP_REQUESTS (
  id NUMBER(19) NOT NULL,
  phone VARCHAR2(20 CHAR) NOT NULL,
  otp_hash VARCHAR2(255 CHAR) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  attempts NUMBER(3) DEFAULT 0 NOT NULL,
  consumed_at TIMESTAMP,
  request_ip_hash VARCHAR2(64 CHAR),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_OTP_REQ PRIMARY KEY (id),
  CONSTRAINT CK_MIRROR_OTP_ATT CHECK (attempts >= 0)
);

CREATE INDEX IX_MIRROR_OTP_PHONE_EXP
  ON MIRROR_OTP_REQUESTS (phone, expires_at);

CREATE TABLE MIRROR_SESSIONS (
  id NUMBER(19) NOT NULL,
  user_id NUMBER(19) NOT NULL,
  token_hash VARCHAR2(64 CHAR) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_SESSIONS PRIMARY KEY (id),
  CONSTRAINT UK_MIRROR_SESSION_TOKEN UNIQUE (token_hash),
  CONSTRAINT FK_MIRROR_SESSION_USER FOREIGN KEY (user_id)
    REFERENCES MIRROR_USERS (id)
);

CREATE INDEX IX_MIRROR_SESSION_USER
  ON MIRROR_SESSIONS (user_id, expires_at);

CREATE TABLE MIRROR_POTHOLES (
  id NUMBER(19) NOT NULL,
  public_id VARCHAR2(30 CHAR) NOT NULL,
  latitude NUMBER(10, 7) NOT NULL,
  longitude NUMBER(10, 7) NOT NULL,
  severity VARCHAR2(20 CHAR) NOT NULL,
  current_status VARCHAR2(30 CHAR) DEFAULT 'reported' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_POTHOLES PRIMARY KEY (id),
  CONSTRAINT UK_MIRROR_POT_PUBLIC UNIQUE (public_id),
  CONSTRAINT CK_MIRROR_POT_LAT CHECK (latitude BETWEEN -90 AND 90),
  CONSTRAINT CK_MIRROR_POT_LON CHECK (longitude BETWEEN -180 AND 180),
  CONSTRAINT CK_MIRROR_POT_SEV CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  CONSTRAINT CK_MIRROR_POT_STATUS CHECK (
    current_status IN ('reported', 'verified', 'assigned', 'in_progress', 'repaired', 'reopened', 'escalated', 'closed')
  )
);

CREATE TABLE MIRROR_REPORTS (
  id NUMBER(19) NOT NULL,
  report_id VARCHAR2(30 CHAR) NOT NULL,
  pothole_id NUMBER(19) NOT NULL,
  citizen_id NUMBER(19) NOT NULL,
  description CLOB,
  submitted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_REPORTS PRIMARY KEY (id),
  CONSTRAINT UK_MIRROR_REPORT_ID UNIQUE (report_id),
  CONSTRAINT FK_MIRROR_REPORT_POT FOREIGN KEY (pothole_id)
    REFERENCES MIRROR_POTHOLES (id),
  CONSTRAINT FK_MIRROR_REPORT_USER FOREIGN KEY (citizen_id)
    REFERENCES MIRROR_USERS (id)
);

CREATE INDEX IX_MIRROR_REPORT_USER
  ON MIRROR_REPORTS (citizen_id, submitted_at);

CREATE TABLE MIRROR_REPORT_PHOTOS (
  id NUMBER(19) NOT NULL,
  report_id NUMBER(19) NOT NULL,
  object_key VARCHAR2(500 CHAR) NOT NULL,
  mime_type VARCHAR2(100 CHAR) NOT NULL,
  file_size NUMBER(19) NOT NULL,
  evidence_type VARCHAR2(20 CHAR) DEFAULT 'before' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_PHOTOS PRIMARY KEY (id),
  CONSTRAINT UK_MIRROR_PHOTO_KEY UNIQUE (object_key),
  CONSTRAINT FK_MIRROR_PHOTO_REPORT FOREIGN KEY (report_id)
    REFERENCES MIRROR_REPORTS (id),
  CONSTRAINT CK_MIRROR_PHOTO_SIZE CHECK (file_size > 0),
  CONSTRAINT CK_MIRROR_PHOTO_TYPE CHECK (evidence_type IN ('before', 'after'))
);

CREATE TABLE MIRROR_STATUS_HISTORY (
  id NUMBER(19) NOT NULL,
  report_id NUMBER(19) NOT NULL,
  old_status VARCHAR2(30 CHAR),
  new_status VARCHAR2(30 CHAR) NOT NULL,
  changed_by NUMBER(19),
  comments VARCHAR2(1000 CHAR),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_STATUS PRIMARY KEY (id),
  CONSTRAINT FK_MIRROR_STATUS_REPORT FOREIGN KEY (report_id)
    REFERENCES MIRROR_REPORTS (id),
  CONSTRAINT FK_MIRROR_STATUS_USER FOREIGN KEY (changed_by)
    REFERENCES MIRROR_USERS (id)
);

CREATE INDEX IX_MIRROR_STATUS_REPORT
  ON MIRROR_STATUS_HISTORY (report_id, created_at);

CREATE TABLE MIRROR_AUDIT_LOGS (
  id NUMBER(19) NOT NULL,
  actor_user_id NUMBER(19),
  action VARCHAR2(100 CHAR) NOT NULL,
  entity_type VARCHAR2(50 CHAR) NOT NULL,
  entity_id VARCHAR2(100 CHAR),
  details CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_MIRROR_AUDIT PRIMARY KEY (id),
  CONSTRAINT FK_MIRROR_AUDIT_USER FOREIGN KEY (actor_user_id)
    REFERENCES MIRROR_USERS (id)
);

COMMIT;
